[package]
name = "terminal-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
termsize = "0.1.9"
unicode-width = "0.2.1"
futures = "0.3.31"
rand = "0.9.2"
